import type { LedgerChange, LedgerDocument, LedgerEntry } from './ledger.js'

/**
 * The published view of the ledger (#58): the current criteria and their
 * verification state, written so someone with no QARE installed can read
 * them. The view names the criteria it cannot call current in one of three
 * states: unverified (admitted, never proven by a run), stale (changed after
 * the run that verified them), and quarantined (held for an open conflict
 * question).
 */
export interface VerificationBuckets {
  unverified: string[]
  stale: string[]
  quarantined: string[]
}

export function verificationBuckets(
  entries: LedgerEntry[],
  changes: LedgerChange[],
  quarantined: string[] = [],
): VerificationBuckets {
  const lastVerify = new Map<string, number>()
  const lastEdit = new Map<string, number>()
  for (const change of changes) {
    for (const criterion of change.criteria) {
      const target = change.kind === 'verify' ? lastVerify : lastEdit
      target.set(criterion, change.seq)
    }
  }
  const held = new Set(quarantined)
  const unverified: string[] = []
  const stale: string[] = []
  for (const entry of [...entries].sort(byCriterion)) {
    if (held.has(entry.criterion)) continue
    if (entry.status === 'proposed') {
      unverified.push(entry.criterion)
      continue
    }
    if (entry.status !== 'active') continue
    const verifiedAt = lastVerify.get(entry.criterion)
    const editedAt = lastEdit.get(entry.criterion)
    if (verifiedAt === undefined || (editedAt !== undefined && editedAt > verifiedAt))
      stale.push(entry.criterion)
  }
  return { unverified, stale, quarantined: [...held].sort() }
}

function byCriterion(a: LedgerEntry, b: LedgerEntry): number {
  return a.criterion < b.criterion ? -1 : a.criterion > b.criterion ? 1 : 0
}

function names(criteria: string[]): string {
  return criteria.length === 0 ? criteria.join(', ') : criteria.join('`, `')
}

export function renderCriteriaMarkdown(
  document: LedgerDocument,
  quarantined: string[] = [],
): string {
  const buckets = verificationBuckets(document.entries, document.changes, quarantined)
  const active = document.entries
    .filter((entry) => entry.status === 'active')
    .sort(byCriterion)
  const verifiedAt = lastVerifiedAt(document.changes)
  const lines: string[] = [
    '# Criteria',
    '',
    'The current acceptance criteria and their verification state, published',
    'from the criteria ledger so someone with no QARE installed can read them.',
    'Generated by `qare ledger publish`; do not edit by hand: the ledger, not',
    'this file, is the store.',
    '',
    `Current criteria: ${document.entries.length} total, ${active.length} active.`,
    '',
  ]
  if (active.length > 0) {
    lines.push('## Verified criteria', '')
    lines.push('| Criterion | Proof | Verified at |')
    lines.push('| --- | --- | --- |')
    for (const entry of active) {
      lines.push(
        `| ${entry.criterion} (${entry.note ?? entry.text ?? ''}) | ${entry.proof} | ${verifiedAt.get(entry.criterion) ?? 'never'} |`,
      )
    }
    lines.push('')
  }
  lines.push(section('Unverified', buckets.unverified, 'admitted but never proven by a run'))
  lines.push(section('Stale', buckets.stale, 'changed after the run that last verified them'))
  lines.push(
    section(
      'Quarantined',
      buckets.quarantined,
      'held for an open conflict question; the run reports them unverified until someone answers',
    ),
  )
  const superseded = document.entries.filter((entry) => entry.status === 'superseded').sort(byCriterion)
  const retired = document.entries.filter((entry) => entry.status === 'retired').sort(byCriterion)
  if (superseded.length > 0 || retired.length > 0) {
    lines.push('## History keepers', '')
    for (const entry of superseded) lines.push(`- ${entry.criterion}: superseded, kept in history`)
    for (const entry of retired) lines.push(`- ${entry.criterion}: retired with a reason, kept in history`)
    lines.push('')
  }
  return `${lines.join('\n').replace(/\n+$/, '')}\n`
}

function section(title: string, criteria: string[], meaning: string): string {
  if (criteria.length === 0) return ''
  return [
    `## ${title}`,
    '',
    `Criteria here are ${meaning}: ${names(criteria)}.`,
    '',
  ].join('\n')
}

function lastVerifiedAt(changes: LedgerChange[]): Map<string, string> {
  const at = new Map<string, string>()
  for (const change of changes) {
    if (change.kind !== 'verify') continue
    for (const criterion of change.criteria) at.set(criterion, change.timestamp)
  }
  return at
}

export function renderHistoryMarkdown(changes: LedgerChange[]): string {
  const lines = [
    '# Ledger history',
    '',
    'Every change to the criteria ledger, in the order it was made. Each',
    'record names who made the change, when, and why; the records are chained,',
    'so history is never rewritten.',
    '',
  ]
  if (changes.length === 0) {
    lines.push('No changes recorded yet.')
    return `${lines.join('\n')}\n`
  }
  for (const change of changes) {
    const touched = change.criteria.length === 0 ? '' : ` (${names(change.criteria)})`
    lines.push(`- ${change.seq}. ${change.kind} by ${change.actor} at ${change.timestamp}: ${change.reason}${touched}`)
  }
  return `${lines.join('\n')}\n`
}
